name = "vaines_org_shop_products"
main = "src/index.js"
compatibility_date = "2024-10-20"

kv_namespaces = [
  { binding = "PRODUCT_CACHE_KV", id = "0d94419b8b5f48eebf97c20ece67933a" }
]

[observability]
enabled = true

[vars]
CACHE_EXPIRATION_MINUTES = "60"
DEBUG = "true"
SQUARE_API_BASE_URL = "https://connect.squareup.com/v2/"
# SQUARE_ACCESS_TOKEN="" # Encrypted secret in the console
# LOCATION_ID = "" # Encrypted secret in the console