name = "vaines_org_shop_products"
main = "src/index.js"
compatibility_date = "2024-10-20"

kv_namespaces = [
  { binding = "KV_NAMESPACE", id = "fbd0e989b4234b2b9e606fc539320a58" }
]

[observability]
enabled = true

[vars]
CACHE_EXPIRATION_MINUTES = "60"
DEBUG = "true"
SQUARE_API_BASE_URL = "https://connect.squareup.com/v2/"
